new version of structEdit
celements/celements-web pull request #101
Opened 2018-05-14 16:05 UTC by dkhasham

https://synjira.atlassian.net/browse/CELDEV-679

2018-05-15 07:44 UTC, fpichler requested changes

2018-05-15 07:44 UTC, fpichler commented on pom.xml
> +      <version>4.7.12-celRTE</version>
it must be possible to use the old and the new tinyMCE or only one of them. Thus we problably need a new project for tinymce4 something like celRTE4?

2018-05-23 21:20 UTC, fpichler approved these changes

2018-05-29 09:26 UTC, msladek approved these changes

2018-07-18 14:53 UTC, merged