JAX-RS 2.0 (Jersey)
celements/celements-web pull request #114
Opened 2018-06-25 04:03 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-717

In web.xml commented out restlet. Also added added missing out comments from syncel.

2018-06-25 09:07 UTC, fpichler requested changes

2018-06-25 09:07 UTC, fpichler commented on pom.xml
> +          <artifactId>*</artifactId>
why is this change needed?

2018-06-25 12:37 UTC, msladek commented on pom.xml
> +          <artifactId>*</artifactId>
`batik-rasterizer` only has one dependency, `batik-transcoder`. but it is already included in a newer version from `org.apache.xmlgraphics-fop`, hence i've now only excluded the transcoder.

2018-06-26 16:39 UTC, fpichler approved these changes

2018-06-26 16:41 UTC, merged