CleverReach REST
celements/celements-web pull request #139
Opened 2018-12-19 14:23 UTC by ebeutler

https://synjira.atlassian.net/browse/CELDEV-638

2018-12-19 17:18 UTC, fpichler submitted a review, later dismissed

2018-12-25 20:37 UTC, fpichler requested changes

2018-12-25 20:37 UTC, fpichler commented on src/main/webapp/WEB-INF/xwiki.properties
> +celements.classdefinition.active=auth
What for do we need to activate "auth" package in celements-web on default? I think this schould be only done in projects using CleverReach component.

2019-01-04 20:31 UTC, fpichler approved these changes

2019-01-04 20:33 UTC, fpichler submitted a review, later dismissed

2019-01-22 14:21 UTC, msladek approved these changes

2019-01-29 11:55 UTC, merged