CELDEV-787 JS EventManager
celements/celements-web pull request #153
Opened 2019-02-11 18:10 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-787

2019-02-13 22:53 UTC, fpichler requested changes

2019-02-13 22:53 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +      _instructionRegex : new RegExp('([\\w]+)([%+-])([\\w-]+):([^?]+)\\??(.+)?'),
```suggestion
      _instructionRegex : new RegExp('([\\w:]+)([%+-])([\\w-]+):([^?]+)\\??(.+)?'),
```

2019-02-13 22:53 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +        if (data.eventName === 'load') {
you can delete this block. The developer should directly use the cel:-event. Please add this functionality to the documentation.

2019-02-13 22:53 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +          htmlElem.fire('cel:onEventInitialized');
please use shorter event-name for example:
```suggestion
          htmlElem.fire('celEM:init');
```

2019-02-14 07:51 UTC, fpichler requested changes

2019-02-14 07:51 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +          if (!isInBody || changedDataValue || !elem.htmlElem.hasClassName('celOnEventInit')) {
For which possible situation is the check on classname needed? The contract is, that elements with the celOnEventInit class are initalized and thus have a representation in the _me._eventElements the class is added after initialization and removed only here after resetting the handlers.

2019-02-14 13:26 UTC, msladek commented on src/main/webapp/resources/celJS/initCelements.js
> +          if (!isInBody || changedDataValue || !elem.htmlElem.hasClassName('celOnEventInit')) {
the check ensures correct handling if the init class was removed. e.g. manually when developing new layouts to test out functionality.
without this check, the element could be contained multiple times in the elements list.

2019-02-14 15:44 UTC, fpichler approved these changes

2019-02-14 15:44 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +          if (!isInBody || changedDataValue || !elem.htmlElem.hasClassName('celOnEventInit')) {
👍

2019-02-14 16:48 UTC, merged