remove old meta tag implementation CELDEV-751
celements/celements-web pull request #169
Opened 2019-06-07 15:17 UTC by ebeutler

https://synjira.atlassian.net/browse/CELDEV-751

2019-06-10 15:09 UTC, fpichler requested changes

2019-06-10 15:09 UTC, fpichler commented on src/main/webapp/templates/celMacros/finaliseHeader.vm
> +#end
moving the 'end' below the '<meta ... />' output leads to a change in behaviour. There will only be an output if "metaTagKey" equals 'refresh'. I guess this is wrong...

2019-06-14 15:55 UTC, ebeutler commented on src/main/webapp/templates/celMacros/finaliseHeader.vm
> +#end
No, that's exactly the intention. All other meta tags should be handled by the BaseObjectMetaTagProvider, just the "special case 'refresh'" remains here, since it has 'http-equiv' as attribute name.

2019-06-14 16:33 UTC, fpichler approved these changes

2019-07-05 16:51 UTC, merged