initAllMultiselect on celBootstrap
celements/celements-web pull request #199
Opened 2020-01-23 18:07 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-861

2020-01-24 09:46 UTC, fpichler requested changes

2020-01-24 09:46 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +        var bootstrapCfg = JSON.parse(this.getAttribute('data-bootstrapConfig')
using 'this' is ubiquitous and a slippery slope because it can change quickly, implicitly and unexpected. Instead go for best-practices and set a variable at the beginning of the method to 'this' and use the variable instead.

2020-01-24 09:46 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +                                   || this.getAttribute('data-multiselectAttr')); // deprecated
can you please add a "Warn" logging for deprecated usage of 'celMultiselect' if encountered?

2020-01-28 08:02 UTC, fpichler requested changes

2020-01-28 08:02 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +     * Bsp Read selected values:
'E.g.' instead of 'Bsp' -> please keep comments in english

2020-01-28 11:18 UTC, msladek commented on src/main/webapp/resources/celJS/initCelements.js
> +     * Bsp Read selected values:
i only extracted this method, I don't know if the comments are needed at all

2020-01-28 12:57 UTC, fpichler approved these changes

2020-01-28 15:05 UTC, merged