update search and model
celements/celements-web pull request #206
Opened 2020-02-18 13:09 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-870

2020-02-20 19:43 UTC, fpichler commented
CELDEV-870 is the wrong issue for the JavaScript Event-Manager extension.

2020-02-20 19:48 UTC, fpichler requested changes
add a proper CELDEV issue to document the improvement in the release notes. Remove the brakeing 'origin' change and keep the '^' enhancement of the css selector.

2020-02-20 19:48 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> -          _me._conditionFunction = new Function('me', 'return ' + condition + ';');
changing the first parameter is a nogo. This is braking all existing implementations.
Furthermore I prefer to NOT extend the jsCondition for security reasons.

2020-02-20 19:48 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +          if (!_me._conditionFunction || _me._conditionFunction(_me._htmlElement, targetElement)) {
changing the first parameter is a nogo. This is braking all existing implementations. It is not backwards compatible.

2020-02-20 22:04 UTC, msladek commented on src/main/webapp/resources/celJS/initCelements.js
> -          _me._conditionFunction = new Function('me', 'return ' + condition + ';');
I require the origin parameter for another issue. In what way does it raise the already existing security concern (which we have addressed by limiting the condition to a single statement) ?

2020-02-20 22:49 UTC, msladek commented on src/main/webapp/resources/celJS/initCelements.js
> +          if (!_me._conditionFunction || _me._conditionFunction(_me._htmlElement, targetElement)) {
the only usage of `_conditionFunction` can only be on this line, where the parameter order is correct. the condition string uses `me` to reference the `targetElement`, hence it doesn't depend on the order.

2020-02-21 08:46 UTC, fpichler approved these changes

2020-02-21 09:51 UTC, merged