CELDEV-869 - PresentationEdit double JS files break save
celements/celements-web pull request #254
Opened 2021-03-22 01:20 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-869

2021-03-27 02:06 UTC, msladek requested changes

2021-03-27 02:06 UTC, msladek commented on src/main/webapp/resources/celJS/initCelements.js
> +  if (typeof window.CELEMENTS == "undefined") { window.CELEMENTS = {}; }
already checked & defined at line 52
```suggestion
```

2021-03-27 02:06 UTC, msladek commented on src/main/webapp/resources/celJS/initCelements.js
> +          const tryEv1 = _me._htmlElem.fire('celements:AjaxReconnectTrying', _me._reconnectWait);
move outside of `if` instead of repeating `tryEv1/2` in else block

2021-03-27 02:06 UTC, msladek commented on src/main/webapp/resources/celJS/initCelements.js
> +      let paramSplit = search.split(new RegExp('[?&]'))
`paramSplit` is never reassigned
```suggestion
      const paramSplit = search.split(new RegExp('[?&]'))
```

2021-03-27 02:06 UTC, msladek commented on src/main/webapp/resources/celJS/initCelements.js
> +          let newMessages = transport.responseText.evalJSON();
`newMessages` is never reassigned
```suggestion
          const newMessages = transport.responseText.evalJSON();
```

2021-03-27 02:06 UTC, msladek commented on src/main/webapp/resources/celJS/initCelements.js
> +  let formValidations = new Hash();
`formValidations` is never reassigned
```suggestion
  const formValidations = new Hash();
```

2021-04-01 15:06 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +          const tryEv1 = _me._htmlElem.fire('celements:AjaxReconnectTrying', _me._reconnectWait);
Unfortunately this is not the same semantic because of leading `_me._reconnectorExecuter.stop();` in the first case. Yet, I extracted the fire in a method.

2021-04-03 12:56 UTC, msladek approved these changes

2021-04-03 17:47 UTC, merged