CELDEV-952 - drop IE < 9 support and correct transform-scale
celements/celements-web pull request #255
Opened 2021-03-24 08:28 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-952

2021-03-27 02:19 UTC, msladek requested changes

2021-03-27 02:19 UTC, msladek commented on src/main/webapp/resources/celJS/celpresentation/CelementsSlideShow.js
> +        let params = {
`params` is never reassigned
```suggestion
        const params = {
```

2021-03-27 02:19 UTC, msladek commented on src/main/webapp/resources/celJS/celpresentation/CelementsSlideShow.js
> +          console.log('_centerCurrentSlide slideRoot dim: ', _me._htmlContainerId, slideOuterWidth,
```suggestion
          console.debug('_centerCurrentSlide slideRoot dim: ', _me._htmlContainerId, slideOuterWidth,
```
and all following occurences of `console.log` within debug check

2021-03-27 02:19 UTC, msladek commented on src/main/webapp/resources/celJS/mobile/MobileSupport.js
> +      let zoomStyles = {};
```suggestion
      const zoomStyles = {};
```

2021-03-31 07:44 UTC, fpichler commented on src/main/webapp/resources/celJS/celpresentation/CelementsSlideShow.js
> +        let params = {
Not true. See line 549

2021-03-31 14:19 UTC, msladek approved these changes

2021-03-31 14:56 UTC, merged