CELDEV-965 - Sitemap reordering fails with JS exception
celements/celements-web pull request #262
Opened 2021-05-02 11:05 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-965

2021-05-05 17:55 UTC, msladek requested changes

2021-05-05 17:55 UTC, msladek commented on src/main/webapp/resources/celJS/navigation/reorderMenuItems.js
> +  if (typeof window.CELEMENTS.reorder == "undefined") { window.CELEMENTS.reorder = {}; }
```suggestion
  if (typeof window.CELEMENTS === "undefined") { window.CELEMENTS = {}; }
  if (typeof window.CELEMENTS.reorder === "undefined") { window.CELEMENTS.reorder = {}; }
```

2021-05-05 17:55 UTC, msladek commented on src/main/webapp/templates/celContextMenu/cel_cm_presentationeditor_nodes/add_cell.vm
> +#set($l = $doc.getURL('view', 'xpage=overlay&conf=AddPage'))
```suggestion
#set($l = $services.url.getURL($doc.documentReference, 'view', 'xpage=overlay&conf=AddPage'))
```

2021-05-05 17:55 UTC, msladek commented on src/main/webapp/templates/celContextMenu/cel_cm_presentationeditor_nodes/add_cell.vm
> +#set($cmenu_pageLink = "${l}&menu_position=&language=${default_language}&redirmode=editMenu")
hand the entire query string to `services.url.getURL(...)`

2021-05-05 17:55 UTC, msladek commented on src/main/webapp/templates/celContextMenu/cel_cm_presentationeditor_nodes/add_sub_cell.vm
> +#if(("$!elemId" != '') && ($services.treeNode.getMaxConfiguredNavigationLevel() > $celementsweb.getDocumentParentsList($elemId, true).size()))
use `WebUtilsScriptService.getDocumentParentsDocRefList(DocumentReference, boolean)` instead.
consider extracting variables for better readability.

2021-05-05 17:55 UTC, msladek commented on src/main/webapp/templates/celContextMenu/cel_cm_presentationeditor_nodes/add_sub_cell.vm
> +#if("$!overwriteWeb" == '')
always true, remove if or line#2

2021-05-05 17:55 UTC, msladek commented on src/main/webapp/templates/celContextMenu/cel_cm_presentationeditor_nodes/add_sub_cell.vm
> +#set($cmenu_pageLink = "${l}&xredirect=$escapetool.url($doc.getURL('view'))")
same points as above

2021-05-05 17:55 UTC, msladek commented on src/main/webapp/templates/celContextMenu/cel_cm_presentationeditor_nodes/del_cell.vm
> +#set($l = "${l}&quot;$xwiki.getURL($elemId,'view', $params)")
use `services.url`

2021-05-05 17:55 UTC, msladek commented on src/main/webapp/templates/celMacros/SitemapForSpace.vm
> +		<option label="$spaceNameSelect" value="$doc.getURL('view', $defaultParams)"##
```suggestion
  #getDefaultParams($spaceNameSelect)
    <option label="$spaceNameSelect" value="$services.url.getURL($doc.documentReference, 'view', $defaultParams)"##
```

2021-05-05 17:55 UTC, msladek commented on src/main/webapp/templates/celMacros/SitemapForSpace.vm
> +#if("$!spaceName" == "$!spaceNameSelect") selected #end>$spaceName</option>
```suggestion
#if("$!spaceName" == "$!spaceNameSelect") selected #end>$spaceNameSelect</option>

```

2021-05-06 04:36 UTC, fpichler commented on src/main/webapp/templates/celContextMenu/cel_cm_presentationeditor_nodes/add_sub_cell.vm
> +#if("$!overwriteWeb" == '')
don't see why this is always true. If line 5 (now lin 7) sets $overwriteWeb to elemParams 1 which could be non empty.

2021-05-06 11:01 UTC, msladek commented on src/main/webapp/templates/celContextMenu/cel_cm_presentationeditor_nodes/add_sub_cell.vm
> +#if("$!overwriteWeb" == '')
yes, my bad

2021-05-06 11:18 UTC, msladek requested changes

2021-05-06 11:18 UTC, msladek commented on src/main/webapp/templates/celContextMenu/cel_cm_presentationeditor_nodes/add_cell.vm
> +#set($cmenu_pageLink = $services.url.getURL($doc.documentReference, 'view', "{l}"))
```suggestion
#set($cmenu_pageLink = $services.url.getURL($doc.documentReference, 'view', "${l}"))
```

2021-05-06 11:18 UTC, msladek commented on src/main/webapp/templates/celContextMenu/cel_cm_presentationeditor_nodes/add_sub_cell.vm
> +#set($l = "${l}&xredirect=$escapetool.url($doc.getURL('view'))")
```suggestion
#set($l = "${l}&xredirect=$escapetool.url($services.url.getURL($doc.documentReference, 'view'))")
```

2021-05-06 15:27 UTC, msladek approved these changes

2021-05-06 16:23 UTC, merged