JS Intersection Observer reliability
celements/celements-web pull request #264
Opened 2021-05-09 19:12 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-966

2021-05-10 11:27 UTC, fpichler commented
"new IntersectionObserver" is not working in IE11. Please add an failing gracefully with a warn-note in the console and not an exception which is canceling all JavaScript excecution.

2021-05-10 11:57 UTC, fpichler requested changes

2021-05-10 11:57 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +      _eventElemCounter: 0,
do not use static class properties (except for constants). It is difficult to understand there behaviour and mostly not needed. Define the property as undefined and initialize in Initializer method.

2021-05-10 11:57 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +          htmlElem.classList.add('celOnEventInit');
not working on IE11. We agreed to still support IE11 on Open-Celements 5.x / see https://synjira.atlassian.net/wiki/spaces/CELDEV/pages/952795152/Open-Celements+5

2021-05-10 11:57 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +          htmlElem.classList.add('celOnEventInit');
Because the IntersectionObeserver API is not working on IE11 at all, it may be better to fail gracefully on initialization of the event manager if IE11 or unsported browser is used.

2021-05-10 11:57 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +            elem.eventHandlers.forEach(handler => handler.unregister());
Arrow functions are not supported in IE11. Please test in IE11 that the JS-Parser can handle it.

2021-05-10 12:09 UTC, msladek commented on src/main/webapp/resources/celJS/initCelements.js
> +          htmlElem.classList.add('celOnEventInit');
classList add/remove with single arguments is supported in IE10+
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

2021-05-10 13:20 UTC, fpichler submitted a review, later dismissed

2021-05-10 13:20 UTC, fpichler commented
Please update minified version of initCelements.js

2021-05-11 03:52 UTC, fpichler approved these changes

2021-05-11 08:39 UTC, merged