CELDEV-994 - add 'defer' and 'async' support to JSScriptService calls
celements/celements-web pull request #288
Opened 2022-01-20 13:42 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-994

2022-01-21 15:46 UTC, msladek requested changes

2022-01-21 15:46 UTC, msladek commented on src/main/webapp/templates/celMacros/loadBackend.vm
> +  $!jsService.includeExtJsFile($extJsParamDefer.setJsFile(':celJS/supportLink/supportLink.js'))
is the builder intended to be reusable? does `includeExtJsFile` modify the builders' state?
if yes & no -> approve

2022-01-21 15:46 UTC, msladek commented on src/main/webapp/templates/celMacros/DarkBox.vm
>  #end
```suggestion
#end

```

2022-01-21 15:46 UTC, msladek commented on src/main/webapp/resources/celJS/validation.js
> +})(window);
```suggestion
})(window);

```

2022-01-21 15:46 UTC, msladek commented on src/main/webapp/resources/celJS/validation.js
> +        return nr == $A(options).findAll(function(elm) {
replace all `findAll` with `filter`

2022-01-21 15:46 UTC, msladek commented on src/main/webapp/resources/celJS/validation.js
> +        const elmWrapper = elm.up('.validation-field-wrapper');
replace all `up` with `clostest`

2022-01-21 15:46 UTC, msladek commented on src/main/webapp/resources/celJS/validation.js
> +      return result = cn.all(function(value) {
replace all `all` with `every`

2022-01-21 15:46 UTC, msladek commented on src/main/webapp/resources/celJS/validation.js
> +        elm.addClassName('validation-passed');
replace all `remove/addClassName` with `classList` manipulations

2022-01-21 15:46 UTC, msladek commented on src/main/webapp/resources/celJS/validation.js
> +          return $A(options).any(function(elm) {
`any` -> `some`

2022-01-24 05:02 UTC, fpichler commented on src/main/webapp/templates/celMacros/loadBackend.vm
> +  $!jsService.includeExtJsFile($extJsParamDefer.setJsFile(':celJS/supportLink/supportLink.js'))
builder is reusable. Added javadoc to the builder class https://github.com/celements/celements-core/pull/296/files

2022-01-24 05:23 UTC, fpichler commented
Added new issue for refactoring/rewriting validation.js
https://synjira.atlassian.net/browse/CELDEV-1003

2022-01-26 13:54 UTC, msladek approved these changes

2022-01-26 14:32 UTC, merged