CELDEV-1037 - ES6 JavaScript module for Dynamic-Loading
celements/celements-web pull request #315
Opened 2022-06-13 07:26 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-1037

2022-06-17 09:50 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +        bubles: true,
```suggestion
        bubbles: true,
```
fix typo everywhere

2022-06-17 09:50 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +      });
```suggestion
      .then(txt => this._updateContent(this._parseHTML(txt)));
```

2022-06-21 13:02 UTC, msladek requested changes

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celEvent.mjs
> +    'memo' : memo
```suggestion
    'memo' : memo,
    'detail' : memo
```
also make [CustomEvent.detail](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#parameters) work

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celEvent.mjs
> +    'memo' : memo
does `memo` even work as intended? if I execute it in the browser:
```
> new CustomEvent("myEvent", { 'memo' : 'hello world' }).memo;
< undefined
```

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +  }
why not inlined?
```suggestion
      window.celExecOnceAfterMessagesLoaded(
         celMessages => this._startupTimeStamp = celMessages.celmeta.startupTimeStamp);
    }
  }
```

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +      if ((scriptPath.split('/').length > 4) && scriptPath.match('/resources/')) {
```suggestion
      if ((scriptPath.split('/').length > 4) && scriptPath.includes('/resources/')) {
```

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +        isLoaded = true;
```suggestion
        isLoaded = true;
        break;
```
the loop could instead also be simplified by
```
const isLoaded = [...document.getElementsByTagName('script')]
    .some(script => script.src === scriptNewURLLink.href);
```

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    console.log('scriptIsLoaded: return ', isLoaded, scriptURL);
```suggestion
    console.log('jsIsLoaded: return', isLoaded, scriptURL);
```

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +      console.debug('scriptIsLoaded: ', loadedScript.src, scriptNewURLLink);
```suggestion
      console.debug('jsIsLoaded:', loadedScript.src, scriptNewURLLink);
```

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +        isLoaded = true;
```suggestion
        isLoaded = true;
        break;
```
the loop could instead also be simplified like above.

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    this._jsLoadedErrBind = this._jsLoadedErr.bind(this);
can't these binds be inlined? they are only used once

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    return (this.getAttribute('type') || 'text/javascript');
```suggestion
    return jsFileUrl.pathname.endsWith('.mjs') ? 'module'
        : (this.getAttribute('type') || 'text/javascript');

```

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +      });
```suggestion
      newEle.rel = 'stylesheet';
      newEle.href = cssFileSrc;
      newEle.type = (this.getAttribute('type') || 'text/css');
      newEle.media = (this.getAttribute('media') || 'screen');
```
can't all `Object.assign` replaced that way in this PR?

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +        });
```suggestion
        this._addLoadMode(newEle);
        newEle.type = this._getType(jsFileSrc);
        newEle.src = this._lazyLoadUtils.getScriptPath(jsFileSrc);
```
using `Object.assign` that way decreases readability imho.

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    this.attachShadow({mode: 'open'});
```suggestion
    this.attachShadow({ 'mode': 'open' });
```

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    this._fetchResponse = this._loadCell();
why is this additional private class members needed?

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +      .then(txt => this._updateContent(this._parseHTML(txt)));
```suggestion
      .then(resp => resp.text())
      .then(txt => this._parseHTML(txt));
      .then(html => this._updateContent(html));
```

2022-06-21 13:02 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    console.debug('connectedCallback: ', this._fetchResponse);
this leads to double space since spaces are already added between params by the browsers. this applies to most `console` calls in this PR.
```suggestion
    console.debug('connectedCallback:', this._fetchResponse);
```

2022-06-22 04:29 UTC, fpichler commented on src/main/webapp/resources/celDynJS/DynamicLoader/celEvent.mjs
> +    'memo' : memo
removed celEvent because it is not part of this issue. Added https://synjira.atlassian.net/browse/CELDEV-1052

2022-06-22 04:29 UTC, fpichler commented on src/main/webapp/resources/celDynJS/DynamicLoader/celEvent.mjs
> +    'memo' : memo
removed celEvent because it is not part of this issue. Added https://synjira.atlassian.net/browse/CELDEV-1052

2022-06-22 05:01 UTC, fpichler commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    this._jsLoadedErrBind = this._jsLoadedErr.bind(this);
I don't think it is better readable but as you prefer it I refactored

2022-06-22 05:03 UTC, fpichler commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    return (this.getAttribute('type') || 'text/javascript');
This does not make it more readble to me. I prefer my version over your suggestion.

2022-06-22 05:29 UTC, fpichler commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    this._fetchResponse = this._loadCell();
Result es used in connectedCallback. Ajax request is fired at this stage and the result might be already returned on connectedCallback time.

2022-06-22 05:31 UTC, fpichler commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +      .then(txt => this._updateContent(this._parseHTML(txt)));
don't think it makes it better readble.

2022-06-22 05:33 UTC, fpichler commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    console.debug('connectedCallback: ', this._fetchResponse);
don't think this hurts or makes it unreadable. I 've had problemes in the past with no spaces being added. I don't want to test all browsers doing it. Thus I stick to "better safe than sorry"

2022-06-22 16:10 UTC, msladek requested changes

2022-06-22 16:10 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    return (this.getAttribute('type') || 'text/javascript');
```suggestion
    if (jsFileUrl.pathname.endsWith('.mjs')) {
      return 'module';
    }
    return (this.getAttribute('type') || 'text/javascript');
```
the comment wasn't primarily about readability but about code style regarding the missing `{ }` brackets. I merely changed it to a single return statement, but whatever version you prefer.

2022-06-22 16:10 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    newEle.type = this._getType(jsFileSrc);
```suggestion
    this._addLoadMode(newEle);
    newEle.type = this._getType(jsFileSrc);
```
i think this line got lost?

2022-06-22 16:10 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    this._fetchResponse = this._loadCell();
oh, my mistake, I though you were simply renaming the function but `_fetchResponse` is actually the resulting promise. would maybe `_fetchedResponse` or `_fetchPromise` be clearer?

2022-06-22 16:10 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +      .then(txt => this._updateContent(this._parseHTML(txt)));
it only puzzled me somewhat that the `text()` call is in a separate ` then` but `_parseHTML` isn't, whatever you prefer.

2022-06-22 16:10 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    console.debug('connectedCallback: ', this._fetchResponse);
Chromium-based browsers and FF join the object list with a single space. I only ever saw this happen when joining with `+` instead of `,` for obvious reasons.
But doesn't matter much, we should switch to a logging framework anyway ;)

2022-06-22 16:10 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +      => this.fireLoadedErr(this, eventName, message, source, lineno, colno,
by moving `addLoadListener` to the utils class you've changed the context for fireLoaded/Err(**this**, eventName). maybe also pass the component calling `addLoadListener`?
```suggestion
  addLoadListener(elem, item, eventName) {
    elem.addEventListener('load', () => this.fireLoaded(item, eventName));
    elem.addEventListener('error', (message, source, lineno, colno, error)
      => this.fireLoadedErr(item, eventName, message, source, lineno, colno,
```

2022-06-23 06:41 UTC, fpichler commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    return (this.getAttribute('type') || 'text/javascript');
why do you need brackets for only a return statement after the if on the same line?

2022-06-23 06:42 UTC, fpichler commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    this._fetchResponse = this._loadCell();
well, the response of fetch is a promise. It was never different in my knowlege.

2022-06-23 06:46 UTC, fpichler commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +      .then(txt => this._updateContent(this._parseHTML(txt)));
text() returns again a promise because it is consuming the response body buffer and this is async.
https://fetch.spec.whatwg.org/#concept-body-consume-body

2022-06-23 13:36 UTC, ebeutler submitted a review, later dismissed

2022-06-23 14:32 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +      .then(txt => this._updateContent(this._parseHTML(txt)));
Ah, I get it now, thanks for clarifying!

2022-06-23 14:32 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    return (this.getAttribute('type') || 'text/javascript');
it's the code style we agreed on. definitely for java, but also in JS we've consistently added brackets for single line if blocks. I see no good reason to have a different style in JS. not adding brackets is in fact a style that could contribute to bugs, see e.g. heartbleed.

2022-06-23 14:35 UTC, msladek requested changes

2022-06-23 14:35 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +    return (this.getAttribute('type') || 'text/javascript');
it's the code style we agreed on. definitely for java, but also in JS we've consistently added brackets for single line if-blocks. I see no good reason to have a different style in JS. not adding brackets is in fact a style that could contribute to bugs, see e.g. heartbleed. 
```suggestion
    if (jsFileUrl.pathname.endsWith('.mjs')) {
      return 'module';
    }
    return (this.getAttribute('type') || 'text/javascript');
```

2022-06-23 15:54 UTC, msladek approved these changes

2022-06-23 15:56 UTC, merged