CELDEV-1076 - add celLazyLoader.mjs to default js and tinymce6 support
celements/celements-web pull request #344
Opened 2022-12-19 05:22 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-1076

2022-12-19 12:40 UTC, msladek requested changes

2022-12-19 12:40 UTC, msladek commented on src/main/webapp/templates/celAjax/picker/filePickerList.vm
> +#end
`$util.parseInt` already defaults to 0 for empty/nonint strings:
```suggestion
#set($start = $mathtool.max(0, $util.parseInt("$!request.start")))
#set($nb = $mathtool.max(0, $util.parseInt("$!request.nb")))
```

2022-12-19 12:40 UTC, msladek commented on src/main/webapp/templates/celAjax/picker/filePickerList.vm
> +  #set($attachments = $xwiki.celementsweb.getAttachmentListForTagSorted($fileBaseDoc, "$!request.tagList", $comparator, $onlyImages, $start, $nb))
these methods are deprecated. are there no replacements in `$services.webUtils`?

2022-12-19 12:40 UTC, msladek commented on src/main/webapp/resources/celRes/ImageAndFilePicker/ImageAndFilePicker.css
> +    color: black;
```suggestion
  content: "drop files here";
  position: absolute;
  align-items: center;
  display: block;
  top: 50%;
  left: 40%;
  font-size: 50px;
  font-weight: bold;
  color: black;
```

2022-12-19 12:40 UTC, msladek commented on src/main/webapp/resources/celJS/editResize.js
> +      console.log('debugging resize: scrollbox ', scrollbox);
```suggestion
      console.debug('debugging resize: scrollbox ', scrollbox);
```

2022-12-19 12:40 UTC, msladek commented on src/main/webapp/resources/celDynJS/ImageAndFilePicker/ImageAndFilePicker.mjs
> +      }
some code style suggestions:
```suggestion
      if (options.duplicateCheck) {
        [...attachEl.querySelectorAll('.imagePickerWrapper')]
          .filter(imgWrapper => imgWrapper.querySelector('img').src.href == attElemUrl.href)
          .forEach(imgWrapper => imgWrapper.remove());
      }
```

2022-12-19 12:40 UTC, msladek commented on src/main/webapp/resources/celDynJS/ImageAndFilePicker/ImageAndFilePicker.mjs
> +    ).then(data => {
why no async/await?

2022-12-19 12:40 UTC, msladek commented on src/main/webapp/resources/celDynJS/ImageAndFilePicker/ImageAndFilePicker.mjs
> +    fetch('/ajax/picker/filePickerList', {
return the promise, a caller might want to await it.

2022-12-19 12:40 UTC, msladek commented on src/main/webapp/resources/celDynJS/ImageAndFilePicker/ImageAndFilePicker.mjs
> +  }
the methods `renderAttachmentList` and `updateAttachmentList` are fairly long and hard to optically parse. can they be further split?

2022-12-25 14:15 UTC, fpichler commented on src/main/webapp/resources/celDynJS/ImageAndFilePicker/ImageAndFilePicker.mjs
> +  }
see CELDEV-1078

2022-12-26 15:45 UTC, msladek approved these changes

2022-12-26 15:45 UTC, msladek commented on src/main/webapp/templates/celAjax/picker/filePickerList.vm
> +  #set($attachments = $xwiki.celementsweb.getAttachmentListForTagSorted($fileBaseDoc, "$!request.tagList", $comparator, $onlyImages, $start, $nb))
?

2022-12-27 05:11 UTC, merged

2022-12-30 13:26 UTC, fpichler commented on src/main/webapp/templates/celAjax/picker/filePickerList.vm
> +  #set($attachments = $xwiki.celementsweb.getAttachmentListForTagSorted($fileBaseDoc, "$!request.tagList", $comparator, $onlyImages, $start, $nb))
unfortunately not.

2022-12-30 13:26 UTC, fpichler commented on src/main/webapp/templates/celAjax/picker/filePickerList.vm
> +  #set($attachments = $xwiki.celementsweb.getAttachmentListForTagSorted($fileBaseDoc, "$!request.tagList", $comparator, $onlyImages, $start, $nb))
`CelementsWebPluginApi.getAttachmentListForTagSorted` and `CelementsWebPluginApi.getAttachmentListForTagSortedSpace` are the only entry point for scripts. In the deprecation note `WebUtilsService.getAttachmentListSorted` is suggested as a replacement. First WebUtilsService is not accessible from scripts, second it `getAttachmentListSorted` is missing the tag filtering.