CELDEV-1076 - bugfixing for tinymce4
celements/celements-web pull request #349
Opened 2023-01-05 00:01 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-1076

2023-01-05 13:43 UTC, msladek requested changes

2023-01-05 13:43 UTC, msladek commented on src/main/webapp/resources/celDynJS/DynamicLoader/celLazyLoader.mjs
> +        });
```suggestion
        await lastPromise;
        document.head.appendChild(newEle);
        lastPromiseOfLoadingType[elemType] = loadedPromise;
```
NOTE: async needed in function def

2023-01-05 13:43 UTC, msladek commented on src/main/webapp/resources/celJS/contextMenu/contextmenu.js
> +  document.addEventListener('mousedown', myContextMenu.hideBind);
the bind `hideBind` shouldn't be necessary with arrow functions:
```suggestion
  document.addEventListener('mousedown', e => myContextMenu.hide(e));
```
can be replaced everywhere like so

2023-01-05 13:43 UTC, msladek commented on src/main/webapp/resources/celJS/contextMenu/contextmenu.js
>      });
```suggestion
    this.getMenuDiv().style.left = x + 'px';
    this.getMenuDiv().style.top = y + 'px';
```

2023-01-05 13:43 UTC, msladek commented on src/main/webapp/resources/celJS/contextMenu/contextmenu.js
> +  getMenuDiv() {
you could define a [class getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#using_getters_in_classes) instead
```suggestion
  get menuDiv() {
```
and keep the previous usage of `this.menuDiv`

2023-01-05 13:43 UTC, msladek commented on src/main/webapp/resources/celJS/contextMenu/contextmenu.js
> +    this.#menuDiv = undefined;
```suggestion
    this.#menuDiv = null;
```

2023-01-05 13:43 UTC, msladek commented on src/main/webapp/templates/celMacros/loadAdminInterface.vm
> +    $celementsweb.includeCSSPage(':celRes/celTabMenu/tabMenu.css')
```suggestion
    $!services.css.includeCSSPage(':celRes/celTabMenu/tabMenu.css')
```

2023-01-05 13:43 UTC, msladek commented on src/main/webapp/templates/celMacros/loadAdminInterface.vm
> +##  $!jsService.includeExtJsFile($extJsParamDefer.setJsFile(':celJS/adminUi/window.js'))
why commented out ? explain in the comment

2023-01-05 21:47 UTC, fpichler commented on src/main/webapp/templates/celMacros/loadAdminInterface.vm
> +##  $!jsService.includeExtJsFile($extJsParamDefer.setJsFile(':celJS/adminUi/window.js'))
It was already commented out before inlining. As it was commented out for about 10 years, I just removed now :-)

2023-01-06 08:08 UTC, msladek approved these changes

2023-01-06 08:09 UTC, merged