CELDEV-1094 - extend TabEditor with cel-events for tabedit:successfulSaved
celements/celements-web pull request #366
Opened 2023-03-21 14:59 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-1094

2023-03-22 12:01 UTC, msladek requested changes

2023-03-22 12:01 UTC, msladek commented on src/main/webapp/resources/celJS/celTabMenu/TabEditor.js
> +    const savingDialog = _me._getModalDialog();
why is  `_me` needed here? better remove it and replace function expressions within this function with arrow expressions.

2023-03-22 12:01 UTC, msladek commented on src/main/webapp/resources/celJS/celTabMenu/TabEditor.js
>        }
```suggestion
      execCallback && execCallback(transport, jsonResponses, failed);
```

2023-03-22 21:01 UTC, fpichler commented on src/main/webapp/resources/celJS/celTabMenu/TabEditor.js
> +    const savingDialog = _me._getModalDialog();
In this method it is needed in line 971, 974 and 977. Hence it is more comprehensible to consequently use it in this method. Consequently I am using it everywhere in a method or nowhere.

2023-03-23 09:11 UTC, msladek approved these changes

2023-03-23 09:11 UTC, msladek commented on src/main/webapp/resources/celJS/celTabMenu/TabEditor.js
> +    const savingDialog = _me._getModalDialog();
which wouldn't be needed simply by replacing `function(...)` with `(...) =>` on 969. this change feels like a step backwards.

2023-03-23 10:24 UTC, fpichler commented on src/main/webapp/resources/celJS/celTabMenu/TabEditor.js
> +    const savingDialog = _me._getModalDialog();
Added CELDEV-1096 to tackle this issue.

2023-03-23 10:24 UTC, merged