CELDEV-1173 - add a additionalParams attribute to cel-data-img
celements/celements-web pull request #401
Opened 2023-08-23 21:36 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-1173

2023-08-23 21:55 UTC, msladek requested changes

2023-08-23 21:55 UTC, msladek commented on src/main/webapp/resources/celDynJS/celData/cel-data.mjs
> +      return src + del + this.additionalParams;
use URL/URLSearchParams:
```suggestion
      const url = new URL(src);
      for (const [key, value] of new URLSearchParams(this.additionalParams)) {
        url.searchParams.append(key, value);
      }
```

2023-08-23 21:55 UTC, msladek commented on src/main/webapp/resources/celDynJS/celData/cel-data.mjs
> +  urlImageSrc(data) {
is there a need for this method to be public?
```suggestion
  #urlImageSrc(data) {
```

2023-08-23 21:55 UTC, msladek commented on src/main/webapp/resources/celDynJS/celData/cel-data.mjs
> +    return this.getAttribute('additional-params') ?? '';
for clarity I'd prefer this attribute to be named `additional-src-params`

2023-08-24 05:30 UTC, fpichler commented on src/main/webapp/resources/celDynJS/celData/cel-data.mjs
> +  urlImageSrc(data) {
yes, only public methods can be called in subclasses. Therefor it is by design that the CelDataImage is extensible.

2023-08-24 22:28 UTC, msladek approved these changes

2023-08-24 23:32 UTC, merged