Cel Event compatibility with CustomEvent
celements/celements-web pull request #402
Opened 2023-08-24 17:11 UTC by msladek

2023-08-24 21:54 UTC, fpichler requested changes

2023-08-24 21:54 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +      // CustomEvent compatibility
CELEMENTS.mixins.Event has nothing to do with DOM events nor is it in any form related to prototypejs. It was designed in first place to provide a clean observer-pattern not relaying on the DOM tree. I do not see any benefit in mixing these concepts.

2023-08-24 22:03 UTC, msladek commented on src/main/webapp/resources/celJS/initCelements.js
> +      // CustomEvent compatibility
the compatibility is intended for the callback functions. the benefit is in reusing the same callback functions no matter if the event is a celements or DOM event. and it prevents patterns like these:
```
myCallback = event => {
  const detail = event.detail ||  event.memo;
  const target = event.target || event.memo.target;
  ...
}
```

2023-08-29 03:09 UTC, fpichler approved these changes

2023-08-29 10:39 UTC, merged