CELDEV-1181 - Projects Open-Celements Devel...  CELDEV-1181   cel-data-renderer rendering off-screen
celements/celements-web pull request #403
Opened 2023-08-29 02:58 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-1181

2023-08-29 11:53 UTC, msladek requested changes

2023-08-29 11:53 UTC, msladek commented on src/main/webapp/resources/celDynJS/celData/cel-data-renderer.mjs
> +    }
this changes the behaviour when reusing the CelDataRenderer. before the children were removed once per `render` call. now they're only removed once per instance.

maybe use a param `#insertEntry(entryData, replaceChildren)` with forEach index instead?
`data.forEach((entryData, idx) => this.#insertEntry(entryData, idx == 0));`

2023-08-30 03:39 UTC, fpichler commented on src/main/webapp/resources/celDynJS/celData/cel-data-renderer.mjs
> +    }
how is paging (rendering in multiple steps) done?

2023-08-30 17:54 UTC, msladek commented on src/main/webapp/resources/celDynJS/celData/cel-data-renderer.mjs
> +    }
changing the page or size attribute calls `render` in the `attributeChangedCallback`. only the actual data returned by the `dataPromise` (the page elements) should be displayed, thus removing the children on each call is part of the previous contract.

2023-08-31 17:53 UTC, msladek submitted a review, later dismissed

2023-09-03 21:41 UTC, fpichler commented on src/main/webapp/resources/celDynJS/celData/cel-data-renderer.mjs
> +    }
if I understand correctly this means that on "load 10 more" the existing elements plus the 10 elements must be rendered. Therefore all existing elements have to be rerendered each time a few additional ones are added. Right?

2023-09-04 12:41 UTC, msladek approved these changes

2023-09-04 23:36 UTC, merged