CelDataRenderer load then replace
celements/celements-web pull request #409
Opened 2023-09-24 10:32 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-1186

2023-09-24 10:57 UTC, fpichler requested changes

2023-09-24 10:57 UTC, fpichler commented on src/main/webapp/resources/celDynJS/celData/cel-data-renderer.mjs
> +    const loadThenReplacePromise = async () => {
why not
```suggestion
    const loadThenReplacePromise = dataPromise.then((data) => {
      this.remove(removeSelector);
      return data;
    };
```
because in an error-case we do not want to remove the old content.

2023-09-24 11:28 UTC, msladek commented on src/main/webapp/resources/celDynJS/celData/cel-data-renderer.mjs
> +    const loadThenReplacePromise = async () => {
`await dataPromise` already propagates an error.

2023-09-27 22:21 UTC, fpichler approved these changes

2023-09-27 22:36 UTC, merged