PROZHP-142 - Ersatz für Google Analytics auf ProZ
celements/celements-web pull request #427
Opened 2023-12-13 17:54 UTC by fpichler

https://synjira.atlassian.net/browse/PROZHP-142

2023-12-19 06:25 UTC, ebeutler requested changes

2023-12-19 06:25 UTC, ebeutler commented on src/main/webapp/resources/celDynJS/analytics/analyticsQueue.mjs
> +	  this.#analyticsEventQueue = [];
```suggestion
    this.#analyticsEventQueue = [];
```

2023-12-19 06:25 UTC, ebeutler commented on src/main/webapp/resources/celRes/analyticsQueue.js
> +	  Event.observe(window, 'beforeunload', _me._sendMissedHits.bind(_me));
```suggestion
      _me._analyticsEventQueue = new Array();
      _me._analyticsPriorizedEventQueue = new Array();
      _me._addBind = _me.add.bind(_me);
      _me._priorityAddBind = _me.priorityAdd.bind(_me);
      _me._sizeBind = _me.size.bind(_me);
      _me._lowPrioritySizeBind = _me.lowPrioritySize.bind(_me);
      _me._highPrioritySizeBind = _me.highPrioritySize.bind(_me);
      _me._sendHitsBind = _me._sendHits.bind(_me);
      _me._getPrioMsgPartBind = _me._getPrioMsgPart.bind(_me);
      _me._running = true;
      _me._sendHitsBind();
      Event.observe(window, 'beforeunload', _me._sendMissedHits.bind(_me));
```

2023-12-24 12:06 UTC, msladek requested changes

2023-12-24 12:06 UTC, msladek commented on src/main/webapp/resources/celDynJS/analytics/analyticsQueue.mjs
> +  }
```suggestion
  _sendHitsOnce() {
    while (this.highPrioritySize() > 0) {
      const nextHit = this.#analyticsPriorizedEventQueue.shift();
      window._paq.push(['trackEvent', nextHit.params.eventCategory, nextHit.params.eventAction,
        nextHit.params.eventLabel, nextHit.params.eventValue]);
    }
    while (this.lowPrioritySize() > 0) {
      const nextHit = this.#analyticsEventQueue.shift();
      window._paq.push(['trackEvent', nextHit.params.eventCategory, nextHit.params.eventAction,
        nextHit.params.eventLabel, nextHit.params.eventValue]);
    }
  }
```

2023-12-24 12:06 UTC, msladek commented on src/main/webapp/resources/celDynJS/analytics/analyticsQueue.mjs
> +    if ((this.highPrioritySize() + this.size()) > 0) {
```suggestion
    if (this.size() > 0) {
```
`size()` already contains `highPrioritySize()`

2023-12-24 12:06 UTC, msladek commented on src/main/webapp/resources/celDynJS/analytics/analyticsQueue.mjs
> +  _sendHitsOnce() {
change the prefix for private functions to `#`

2023-12-30 07:14 UTC, ebeutler approved these changes

2024-01-01 13:19 UTC, msladek approved these changes

2024-01-02 22:18 UTC, merged