Feature blog article meta tags
celements/celements-web pull request #44
Opened 2017-02-17 16:11 UTC by ebeutler

https://synjira.atlassian.net/browse/CELDEV-389

First merge https://github.com/celements/celements-blog/pull/22

2017-02-18 19:57 UTC, fpichler requested changes

2017-02-18 19:57 UTC, fpichler commented on src/main/webapp/templates/celMacros/includeDefaultHeader.vm
> +#if('Article' == "$!services.pageType.getPageTypeRef($doc.getDocumentReference()).getConfigName()")
please keep displayCollectedMetaTags and add a beforeDisplayCollectedMetaTag event which might be observed by any listener and add additional mediaTag elements before they get displayed. In general please do not add any strong cupling between any extension and celements-web

2017-02-22 16:52 UTC, msladek requested changes

2017-02-22 16:52 UTC, msladek commented on src/main/webapp/templates/celMacros/includeDefaultHeader.vm
> +#if('Article' == "$!services.pageType.getPageTypeRef($doc.getDocumentReference()).getConfigName()")
agree, implement as discussed

2017-02-23 07:10 UTC, ebeutler commented
Refactored.
Core changes on https://github.com/celements/celements-core/pull/104

2017-02-24 14:09 UTC, msladek approved these changes

2017-02-24 14:09 UTC, msladek commented
looks neat now, thanks!

2017-02-26 17:11 UTC, fpichler approved these changes

2017-03-06 13:59 UTC, merged