Main & Central xml docs
celements/celements-web pull request #442
Opened 2024-07-14 23:18 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-1233

2024-07-15 22:15 UTC, fpichler requested changes

2024-07-15 22:15 UTC, fpichler commented on pom.xml
> +      <artifactId>celements-wiki-manager</artifactId>
why removing `celements-user-manager-web`?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/OptionsDropdown/WebHome.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/OptionsDropdown/WebPreferences.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/OptionsDropdown/adduser.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/CelementsContextMenu/cel_cm_celimage_slideshow.xml
Can we move this to the `image-module` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/CelementsContextMenu/cel_cm_gallery.xml
Can we move this to the `image-module` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/CelementsContextMenu/cel_cm_gallery_list.xml
Can we move this to the `image-module` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/CelementsContextMenu/cel_cm_gallery_view.xml
Can we move this to the `image-module` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/CelementsContextMenu/cel_cm_rte_content.xml
Can we move this to the `Celements-RTE` module war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/CelementsContextMenu/cel_cm_structured_data_editor.xml
Can we move this to the `structured-data-editor-web` module war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/OptionsDropdown/dropButton.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/OptionsDropdown/dropdownContent.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/OptionsDropdown/dropdownWrapper.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/OptionsDropdown/export.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/OptionsDropdown/imporrt.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/Article.xml
Can we move this to the `celements-blog-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/BannerCell.xml
I think the Banner-PageType is for a long time deprecated (replaced by the PageDependentContent). Thus, can we drop it instead of moving to disk?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/Blog.xml
Can we move this to the `celements-blog-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/Calendar.xml
Can we move this to the `celements-calendar-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/DirectLinks.xml
I think the DirectLinks-PageType is for a long time deprecated (replaced by the PageDependentContent). Thus, can we drop it instead of moving to disk?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/CelementsContextMenu/cel_cm_blog_article.xml
Can we move this to the `celements-blog-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/BlogTemplates/ArticleClassTemplate.xml
Can we move this to the `celements-blog-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/CalTemplates/Event.xml
Can we move this to the `celements-calendar-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/CelementsContextMenu/cel_cm_calendar_event.xml
Can we move this to the `celements-calendar-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/Event.xml
Can we move this to the `celements-calendar-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/Gallery.xml
Can we move this to the `celements-image-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/GalleryList.xml
Can we move this to the `celements-image-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/ImageSlide.xml
Can we move this to the `celements-image-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/RichText.xml
Can we move this to the `Celements-RTE` module war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/RichTextCell.xml
I think the RichTextCell-PageType is for a long time deprecated (replaced by the PageDependentContent). Thus, can we drop it instead of moving to disk?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/SlideshowCell.xml
Can we move this to the `celements-image-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/TextTicker.xml
Can we move this to the `celements-tickerCell-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/PageTypes/TranslationBoxCell.xml
I think the TranslationBoxCell-PageType is for a long time deprecated (replaced by the PageDependentContent). Thus, can we drop it instead of moving to disk?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/WebHome.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/WebPreferences.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/active.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/arrow_action.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/company.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/editContent.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/delete_action.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/email.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/edit_action.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/language.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/mail_action.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/name.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/vorname.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableRow/WebHome.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableRow/WebPreferences.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableRow/activ.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableRow/arrow_action.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableRow/company.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableRow/email.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableRow/edit_action.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableRow/editContent.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableRow/delete_action.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableHeader/WebHome.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/TableRow/vorname.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/UserAdmin/Titel.xml
looks like it is part of the user manager. Thus can we move this to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/UserAdmin/WebHome.xml
looks like it is part of the user manager. Thus can we move this UserAdmin space to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/UserAdminEdit/WebHome.xml
looks like it is part of the user manager. Thus can we move this UserAdminEdit space to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/UserAdminForm/AjaxMode.xml
looks like it is part of the user manager. Thus can we move this UserAdminForm space to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/celements2web/UserAdminSearch/WebHome.xml
looks like it is part of the user manager. Thus can we move this UserAdminSearch space to the `celements-user-manager-web` war project?

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/xwiki/XWiki/ContentEditorsGroup.xml
I think this ContentEditorsGroup document is not needed. There is a mandatory document java class for the system group documents.

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/xwiki/XWiki/LayoutEditorsGroup.xml
I think this LayoutEditorsGroup document is not needed. There is a mandatory document java class for the system group documents.

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/xwiki/XWiki/XWikiAllGroup.xml
I think this XWikiAllGroup document is not needed. There is a mandatory document java class for the system group documents.

2024-07-15 22:15 UTC, fpichler commented on src/main/webapp/docs/xwiki/XWiki/XWikiAdminGroup.xml
I think this XWikiAdminGroup document is not needed. There is a mandatory document java class for the system group documents.

2024-07-16 06:19 UTC, msladek commented on pom.xml
> +      <artifactId>celements-wiki-manager</artifactId>
it's just moved to L160 where it's more appropriate, not removed

2024-07-22 23:00 UTC, fpichler approved these changes

2024-07-23 07:26 UTC, merged