new jira support link
celements/celements-web pull request #54
Opened 2017-08-14 14:45 UTC by dkhasham

related Ticket: https://synjira.atlassian.net/browse/AIPD-326

2017-08-15 07:46 UTC, fpichler requested changes

2017-08-15 07:46 UTC, fpichler commented on src/main/webapp/resources/celJS/initCelements.js
> +        url: "https://synjira.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-T/-qxrqfl/b/c/3d70dff4c40bd20e976d5936642e2171/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector
this URL is possibly not suited for an open source project. Please move to configuration file.

2017-08-15 07:46 UTC, fpichler commented on src/main/webapp/resources/celJS/adminUi/menubar.js
> -  Cel_Zenbox.show();
where is Cel_Zendbox defined? please remove the old code.

2017-08-15 15:37 UTC, dkhasham commented on src/main/webapp/resources/celJS/adminUi/menubar.js
> -  Cel_Zenbox.show();
old code removed

2017-08-19 00:27 UTC, fpichler requested changes

2017-08-19 00:27 UTC, fpichler commented on src/main/webapp/resources/celJS/supportLink/supportLink.js
> +        url: Validation.messages.get("supportLinkURL"),
please use window.celMessages not Validation messages. Validation is only loaded on a Form-Page.

2017-08-19 00:27 UTC, fpichler commented on src/main/webapp/templates/celMacros/CelValidationMessages.vm
> +$jsonBuilder.addStringProperty('supportLinkURL', "$adminMsg.get('cel_supportLink_url')")
move to celMacros/CelMessages.vm

2017-08-19 11:41 UTC, fpichler commented
please change to CELDEV-533

2017-08-22 14:16 UTC, fpichler commented
duplicate to 55 please remove branch and close PR

2017-08-22 14:22 UTC, closed without merging